//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsApi.UnitTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Xml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Xml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsApi.UnitTest.Xml", typeof(Xml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fsapiResponse&gt;
        ///&lt;status&gt;FS_OK&lt;/status&gt;
        ///&lt;item key=&quot;0&quot;&gt;
        ///&lt;field name=&quot;label&quot;&gt;&lt;c8_array&gt;Mein EQ&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;1&quot;&gt;
        ///&lt;field name=&quot;label&quot;&gt;&lt;c8_array&gt;Normal&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;2&quot;&gt;
        ///&lt;field name=&quot;label&quot;&gt;&lt;c8_array&gt;Mittig&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;3&quot;&gt;
        ///&lt;field name=&quot;label&quot;&gt;&lt;c8_array&gt;Jazz&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;4&quot;&gt;
        ///&lt;field name=&quot;label&quot;&gt;&lt;c8_array&gt;Rock&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;5&quot;&gt;
        ///&lt;field name=&quot;label&quot;&gt;&lt;c8_array&gt;Soundtra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EqualizerPresets {
            get {
                return ResourceManager.GetString("EqualizerPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fsapiResponse&gt;
        ///&lt;status&gt;FS_OK&lt;/status&gt;
        ///&lt;notify node=&quot;netremote.play.info.name&quot;&gt;&lt;value&gt;&lt;c8_array&gt;Lounge FM Vienna&lt;/c8_array&gt;&lt;/value&gt;
        ///&lt;/notify&gt;
        ///&lt;notify node=&quot;netremote.play.info.text&quot;&gt;&lt;value&gt;&lt;c8_array&gt;Coralie Clément - L&amp;apos;Ombre Et La Lumiere&lt;/c8_array&gt;&lt;/value&gt;
        ///&lt;/notify&gt;
        ///&lt;/fsapiResponse&gt;.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fsapiResponse&gt;
        ///&lt;status&gt;FS_OK&lt;/status&gt;
        ///&lt;item key=&quot;0&quot;&gt;
        ///&lt;field name=&quot;name&quot;&gt;&lt;c8_array&gt;&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;1&quot;&gt;
        ///&lt;field name=&quot;name&quot;&gt;&lt;c8_array&gt;&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;2&quot;&gt;
        ///&lt;field name=&quot;name&quot;&gt;&lt;c8_array&gt;&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;3&quot;&gt;
        ///&lt;field name=&quot;name&quot;&gt;&lt;c8_array&gt;&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;4&quot;&gt;
        ///&lt;field name=&quot;name&quot;&gt;&lt;c8_array&gt;&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;5&quot;&gt;
        ///&lt;field name=&quot;name&quot;&gt;&lt;c8_array&gt;&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fsapiResponse&gt;
        ///&lt;status&gt;FS_OK&lt;/status&gt;
        ///&lt;item key=&quot;0&quot;&gt;
        ///&lt;field name=&quot;id&quot;&gt;&lt;c8_array&gt;IR&lt;/c8_array&gt;&lt;/field&gt;
        ///&lt;field name=&quot;selectable&quot;&gt;&lt;u8&gt;1&lt;/u8&gt;&lt;/field&gt;
        ///&lt;field name=&quot;label&quot;&gt;&lt;c8_array&gt;Internet Radio&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;1&quot;&gt;
        ///&lt;field name=&quot;id&quot;&gt;&lt;c8_array&gt;Spotify&lt;/c8_array&gt;&lt;/field&gt;
        ///&lt;field name=&quot;selectable&quot;&gt;&lt;u8&gt;1&lt;/u8&gt;&lt;/field&gt;
        ///&lt;field name=&quot;label&quot;&gt;&lt;c8_array&gt;Spotify&lt;/c8_array&gt;&lt;/field&gt;
        ///
        ///&lt;/item&gt;
        ///&lt;item key=&quot;2&quot;&gt;
        ///&lt;field name=&quot;id&quot;&gt;&lt;c8_array&gt;MP&lt;/c8_array&gt;&lt;/field&gt;
        ///&lt;field name=&quot;selectable&quot;&gt;&lt;u8&gt;1&lt;/u [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RadioModes {
            get {
                return ResourceManager.GetString("RadioModes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fsapiResponse&gt;
        ///&lt;status&gt;FS_TIMEOUT&lt;/status&gt;
        ///&lt;/fsapiResponse&gt;.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
    }
}
